name: ECS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Build and push Docker image
        run: |
          docker build -t your-image-name .
          docker tag your-image-name:latest your-ecr-repository-uri:latest
          docker push your-ecr-repository-uri:latest

      - name: Update ECS service
        run: |
          aws ecs update-service --ecsclus --service ecsservice --force-new-deployment
